services:
  landns-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
        - ./:/workspace
        - landns-dev-vsc:/root/.vscode-server
        - ~/.ssh:/root/.ssh
    stdin_open: true
    tty: true

volumes:
  landns-dev-vsc: